---
- hosts: client
  become: yes
  tasks:
    - name: Install networking tools
      apt:
        name: [net-tools, dnsutils]
        state: present
        update_cache: yes

    - name: Bring down eth1
      command: ip link set eth1 down

    - name: Bring up eth1
      command: ip link set eth1 up

    - name: Request DHCP lease on eth1
      command: dhclient -v eth1
